#!/usr/bin/env python3
"""Load glyph builds (json/<class>.json), resolve names -> GlyphProperties ids,
validate, and generate src/BoostGlyphs.cpp.

json: {"0": {"major": [3 names], "minor": [3 names]}, "1": ..., "2": ...}
"""
import glob, json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import glyphs

HERE = os.path.dirname(__file__)
FILE_TO_CLASS = {k.lower(): k for k in glyphs.CLASS_CONST}


def load_data():
    data = {}
    for f in sorted(glob.glob(os.path.join(HERE, "json", "*.json"))):
        cls = FILE_TO_CLASS.get(os.path.basename(f)[:-5])
        if cls:
            data[cls] = json.load(open(f))
    return data


def validate(data):
    errs = []
    for cls, specs in data.items():
        for si in ("0", "1", "2"):
            _, e = glyphs.build_ids(specs[si])
            errs += [f"{cls}/spec{si}: {x}" for x in e]
    return errs


def generate(data):
    o = []
    o.append("// Generated by tools/boost-glyphs/gen.py - do not edit by hand.")
    o.append("// Preset glyphs per class+spec (GlyphProperties ids), verified against the client DBCs.")
    o.append('#include "BoostGlyphs.h"')
    o.append('#include "DBCStores.h"')
    o.append("")
    o.append("std::vector<uint32> BoostGlyphs::GetGlyphs(uint32 classId, uint8 spec)")
    o.append("{")
    o.append("  switch (classId)")
    o.append("  {")
    for cls in glyphs.CLASS_CONST:
        if cls not in data:
            continue
        o.append(f"  case {glyphs.CLASS_CONST[cls]}:")
        o.append("    switch (spec)")
        o.append("    {")
        for si in ("0", "1", "2"):
            ids, _ = glyphs.build_ids(data[cls][si])
            o.append(f"    case {si}: // {glyphs.SPEC_NAMES[cls][int(si)]}")
            o.append(f"      return {{{', '.join(str(i) for i in ids)}}};")
        o.append("    }")
        o.append("    break;")
    o.append("  default:")
    o.append("    break;")
    o.append("  }")
    o.append("  return {};")
    o.append("}")
    o.append("")
    o.append("void BoostGlyphs::ApplyGlyphs(Player *player, uint8 specialization)")
    o.append("{")
    o.append("  if (specialization > 2)")
    o.append("  {")
    o.append("    specialization = 0;")
    o.append("  }")
    o.append("")
    o.append("  std::vector<uint32> glyphList = GetGlyphs(player->getClass(), specialization);")
    o.append("  if (glyphList.empty())")
    o.append("  {")
    o.append("    return;")
    o.append("  }")
    o.append("")
    o.append("  // Place each glyph into the first free slot whose type matches (major/minor).")
    o.append("  std::vector<bool> used(glyphList.size(), false);")
    o.append("  for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)")
    o.append("  {")
    o.append("    GlyphSlotEntry const *gs = sGlyphSlotStore.LookupEntry(player->GetGlyphSlot(slot));")
    o.append("    if (!gs)")
    o.append("    {")
    o.append("      continue;")
    o.append("    }")
    o.append("")
    o.append("    for (size_t i = 0; i < glyphList.size(); ++i)")
    o.append("    {")
    o.append("      if (used[i])")
    o.append("      {")
    o.append("        continue;")
    o.append("      }")
    o.append("      GlyphPropertiesEntry const *gp = sGlyphPropertiesStore.LookupEntry(glyphList[i]);")
    o.append("      if (!gp || gp->TypeFlags != gs->TypeFlags)")
    o.append("      {")
    o.append("        continue;")
    o.append("      }")
    o.append("      if (uint32 oldGlyph = player->GetGlyph(slot))")
    o.append("      {")
    o.append("        if (GlyphPropertiesEntry const *oldGp = sGlyphPropertiesStore.LookupEntry(oldGlyph))")
    o.append("        {")
    o.append("          player->RemoveAurasDueToSpell(oldGp->SpellId);")
    o.append("        }")
    o.append("      }")
    o.append("      player->SetGlyph(slot, glyphList[i], true);")
    o.append("      player->CastSpell(player, gp->SpellId, true);")
    o.append("      used[i] = true;")
    o.append("      break;")
    o.append("    }")
    o.append("  }")
    o.append("")
    o.append("  player->SendTalentsInfoData(false);")
    o.append("}")
    o.append("")
    return "\n".join(o)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "validate"
    data = load_data()
    if cmd == "validate":
        errs = validate(data)
        if errs:
            print("\n".join(errs)); print(f"\n{len(errs)} ERRORS"); sys.exit(1)
        print(f"all glyph builds valid ({len(data)} classes)")
    elif cmd == "generate":
        print(generate(data))
