#!/usr/bin/env python3
"""Load archetypes.json (enchant per slot + gem per socket color), verify ids against
SpellItemEnchantment.dbc, and generate src/BoostGear.cpp.

archetypes.json: {ARCHETYPE: {"enchants": {slot: enchId}, "gems": {color: enchId}}}
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import gear

HERE = os.path.dirname(__file__)
ARCH_ORDER = ["STR_MELEE", "TANK", "AGI_MELEE", "AGI_RANGED", "SP_CASTER", "HEALER"]
COLOR_ORDER = ["meta", "red", "yellow", "blue"]


def load():
    return json.load(open(os.path.join(HERE, "archetypes.json")))


def validate(data):
    errs = []
    for arch in ARCH_ORDER:
        if arch not in data:
            errs.append(f"missing archetype {arch}"); continue
        for slot, eid in data[arch].get("enchants", {}).items():
            if slot not in gear.ENCHANT_SLOTS:
                errs.append(f"{arch}: unknown slot {slot}")
            if not gear.verify(eid):
                errs.append(f"{arch}/{slot}: enchant {eid} not in SpellItemEnchantment.dbc")
        for color, gid in data[arch].get("gems", {}).items():
            if color not in gear.SOCKET_COLORS:
                errs.append(f"{arch}: unknown color {color}")
            if not gear.verify(gid):
                errs.append(f"{arch}/{color}: gem enchant {gid} not in SpellItemEnchantment.dbc")
    return errs


def generate(data):
    o = []
    o.append("// Generated by tools/boost-gear/gen.py - do not edit by hand.")
    o.append("// Per-archetype enchants and gems, verified against 3.3.5a SpellItemEnchantment.dbc.")
    o.append('#include "BoostGear.h"')
    o.append("")
    o.append("namespace")
    o.append("{")
    o.append("  // Archetypes: 0 STR_MELEE, 1 TANK, 2 AGI_MELEE, 3 AGI_RANGED, 4 SP_CASTER, 5 HEALER.")
    o.append("  // Enchant SpellItemEnchantment id per EQUIPMENT_SLOT index (0 = none).")
    o.append("  const uint32 enchantBySlot[6][18] =")
    o.append("  {")
    for arch in ARCH_ORDER:
        row = [0] * 18
        for slot, eid in data[arch].get("enchants", {}).items():
            row[gear.ENCHANT_SLOTS[slot]] = eid
        o.append(f"    {{{', '.join(str(x) for x in row)}}}, // {arch}")
    o.append("  };")
    o.append("")
    o.append("  // Gem enchant id per colour: [meta, red, yellow, blue] (0 = none).")
    o.append("  const uint32 gemByColor[6][4] =")
    o.append("  {")
    for arch in ARCH_ORDER:
        row = [data[arch].get("gems", {}).get(c, 0) for c in COLOR_ORDER]
        o.append(f"    {{{', '.join(str(x) for x in row)}}}, // {arch}")
    o.append("  };")
    o.append("")
    o.append("  int ArchetypeOf(uint32 classId, uint8 spec)")
    o.append("  {")
    o.append("    switch (classId)")
    o.append("    {")
    for cls in gear.CLASS_CONST:
        cases = []
        for s in range(3):
            arch = gear.ARCHETYPE.get((cls, s))
            cases.append(ARCH_ORDER.index(arch))
        o.append(f"    case {gear.CLASS_CONST[cls]}:")
        o.append(f"      return spec == 0 ? {cases[0]} : spec == 1 ? {cases[1]} : {cases[2]};")
    o.append("    }")
    o.append("    return -1;")
    o.append("  }")
    o.append("}")
    o.append("")
    o.append("static uint32 GetEnchant(uint32 classId, uint8 spec, uint8 slot)")
    o.append("{")
    o.append("  int a = ArchetypeOf(classId, spec);")
    o.append("  return (a < 0 || slot >= 18) ? 0 : enchantBySlot[a][slot];")
    o.append("}")
    o.append("")
    o.append("static uint32 GetGem(uint32 classId, uint8 spec, uint32 color)")
    o.append("{")
    o.append("  int a = ArchetypeOf(classId, spec);")
    o.append("  if (a < 0)")
    o.append("  {")
    o.append("    return 0;")
    o.append("  }")
    o.append("  switch (color)")
    o.append("  {")
    o.append("  case 1: return gemByColor[a][0];")
    o.append("  case 2: return gemByColor[a][1];")
    o.append("  case 4: return gemByColor[a][2];")
    o.append("  case 8: return gemByColor[a][3];")
    o.append("  }")
    o.append("  return 0;")
    o.append("}")
    o.append("")
    o.append("void BoostGear::ApplyEnchants(Player *player, uint8 specialization)")
    o.append("{")
    o.append("  for (uint8 slot = EQUIPMENT_SLOT_START; slot < EQUIPMENT_SLOT_TABARD; ++slot)")
    o.append("  {")
    o.append("    Item *item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);")
    o.append("    if (!item)")
    o.append("    {")
    o.append("      continue;")
    o.append("    }")
    o.append("    uint32 ench = GetEnchant(player->getClass(), specialization, slot);")
    o.append("    if (!ench)")
    o.append("    {")
    o.append("      continue;")
    o.append("    }")
    o.append("    item->SetEnchantment(PERM_ENCHANTMENT_SLOT, ench, 0, 0);")
    o.append("    player->ApplyEnchantment(item, PERM_ENCHANTMENT_SLOT, true);")
    o.append("  }")
    o.append("}")
    o.append("")
    o.append("void BoostGear::ApplyGems(Player *player, uint8 specialization)")
    o.append("{")
    o.append("  for (uint8 slot = EQUIPMENT_SLOT_START; slot < EQUIPMENT_SLOT_TABARD; ++slot)")
    o.append("  {")
    o.append("    Item *item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);")
    o.append("    if (!item)")
    o.append("    {")
    o.append("      continue;")
    o.append("    }")
    o.append("    ItemTemplate const *proto = item->GetTemplate();")
    o.append("    for (uint8 i = 0; i < MAX_ITEM_PROTO_SOCKETS; ++i)")
    o.append("    {")
    o.append("      uint32 color = proto->Socket[i].Color;")
    o.append("      if (!color)")
    o.append("      {")
    o.append("        continue;")
    o.append("      }")
    o.append("      uint32 gem = GetGem(player->getClass(), specialization, color);")
    o.append("      if (!gem)")
    o.append("      {")
    o.append("        continue;")
    o.append("      }")
    o.append("      EnchantmentSlot es = EnchantmentSlot(SOCK_ENCHANTMENT_SLOT + i);")
    o.append("      item->SetEnchantment(es, gem, 0, 0);")
    o.append("      player->ApplyEnchantment(item, es, true);")
    o.append("    }")
    o.append("  }")
    o.append("}")
    o.append("")
    return "\n".join(o)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "validate"
    data = load()
    if cmd == "validate":
        errs = validate(data)
        if errs:
            print("\n".join(errs)); print(f"\n{len(errs)} ERRORS"); sys.exit(1)
        print(f"all archetypes valid ({len(data)})")
    elif cmd == "generate":
        print(generate(data))
