#!/usr/bin/env python3
"""Load talent builds (json/<class>.json), resolve talent names -> ids against
Talent.dbc, validate, and generate src/BoostTalents.cpp.

json format: {"0": [["Talent Name", rank], ...], "1": [...], "2": [...]}
ranks are point counts (1..maxrank). Names are matched within the class's trees.
"""
import glob, json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import talents

CLASS_CONST = {
    "WARRIOR": "CLASS_WARRIOR", "PALADIN": "CLASS_PALADIN", "HUNTER": "CLASS_HUNTER",
    "ROGUE": "CLASS_ROGUE", "PRIEST": "CLASS_PRIEST", "DK": "CLASS_DEATH_KNIGHT",
    "SHAMAN": "CLASS_SHAMAN", "MAGE": "CLASS_MAGE", "WARLOCK": "CLASS_WARLOCK",
    "DRUID": "CLASS_DRUID",
}
FILE_TO_CLASS = {k.lower(): k for k in CLASS_CONST}
# Specs that dual-wield but get no Dual Wield (674) from a talent -> learn it explicitly.
EXTRA_SPELLS = {("WARRIOR", 1): [674], ("DK", 1): [674], ("SHAMAN", 1): [674]}

HERE = os.path.dirname(__file__)


def load_data():
    data = {}
    for f in sorted(glob.glob(os.path.join(HERE, "json", "*.json"))):
        cls = FILE_TO_CLASS.get(os.path.basename(f)[:-5])
        if cls:
            data[cls] = json.load(open(f))
    return data


def picks_for(cls, spec_list):
    """Resolve a spec's [[name,rank]] to ordered [(talentId, rank, row, col)]."""
    cid = talents.CLASSES[cls]
    flat = {t["id"]: t for tp in range(3) for t in talents.TREES[cid][tp]}
    out = []
    for name, rank in spec_list:
        tid, _ = talents.resolve(cls, name)
        t = flat[tid]
        out.append((tid, rank, t["row"], t["col"]))
    out.sort(key=lambda x: (x[2], x[3]))
    return out


def validate(data):
    errs = []
    for cls, specs in data.items():
        for si in ("0", "1", "2"):
            named = specs[si]
            try:
                picks = talents.build_from_names(cls, named)
            except KeyError as e:
                errs.append(str(e)); continue
            e2, total, per_tree = talents.validate_build(cls, picks)
            errs += e2
            if total < 60:
                errs.append(f"{cls}/spec{si}: only {total} points spent (build likely incomplete)")
    return errs


def generate(data):
    o = []
    o.append("// Generated by tools/boost-talents/gen.py - do not edit by hand.")
    o.append("// Preset talent build per class+spec, verified against 3.3.5a Talent.dbc.")
    o.append('#include "BoostTalents.h"')
    o.append("")
    o.append("std::vector<std::pair<uint32, uint32>> BoostTalents::GetBuild(uint32 classId, uint8 spec)")
    o.append("{")
    o.append("  switch (classId)")
    o.append("  {")
    for cls in CLASS_CONST:
        if cls not in data:
            continue
        o.append(f"  case {CLASS_CONST[cls]}:")
        o.append("    switch (spec)")
        o.append("    {")
        for si in ("0", "1", "2"):
            picks = picks_for(cls, data[cls][si])
            pairs = ", ".join(f"{{{tid}, {rank}}}" for tid, rank, _, _ in picks)
            o.append(f"    case {si}: // {talents.SPEC_NAMES[cls][int(si)]}")
            o.append(f"      return {{{pairs}}};")
        o.append("    }")
        o.append("    break;")
    o.append("  default:")
    o.append("    break;")
    o.append("  }")
    o.append("  return {};")
    o.append("}")
    o.append("")
    o.append("std::vector<uint32> BoostTalents::GetExtraSpells(uint32 classId, uint8 spec)")
    o.append("{")
    for (cls, si), spells in EXTRA_SPELLS.items():
        lst = ", ".join(str(s) for s in spells)
        o.append(f"  if (classId == {CLASS_CONST[cls]} && spec == {si})")
        o.append(f"  {{")
        o.append(f"    return {{{lst}}};")
        o.append(f"  }}")
    o.append("  return {};")
    o.append("}")
    o.append("")
    o.append("void BoostTalents::ApplyTalents(Player *player, uint8 specialization)")
    o.append("{")
    o.append("  if (specialization > 2)")
    o.append("  {")
    o.append("    specialization = 0;")
    o.append("  }")
    o.append("")
    o.append("  // Start from a clean slate; a level-80 then has its full talent points free.")
    o.append("  player->resetTalents(true);")
    o.append("")
    o.append("  // Baseline abilities a build assumes (e.g. Dual Wield) but the class is not taught.")
    o.append("  for (uint32 spellId : GetExtraSpells(player->getClass(), specialization))")
    o.append("  {")
    o.append("    player->learnSpell(spellId, false);")
    o.append("  }")
    o.append("")
    o.append("  // Picks are pre-sorted by tier, so prerequisites/tier minimums are satisfied as we go.")
    o.append("  for (auto const &pick : GetBuild(player->getClass(), specialization))")
    o.append("  {")
    o.append("    for (uint32 r = 0; r < pick.second; ++r)")
    o.append("    {")
    o.append("      player->LearnTalent(pick.first, r);")
    o.append("    }")
    o.append("  }")
    o.append("")
    o.append("  player->SendTalentsInfoData(false);")
    o.append("}")
    o.append("")
    return "\n".join(o)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "validate"
    data = load_data()
    if cmd == "validate":
        errs = validate(data)
        if errs:
            print("\n".join(errs)); print(f"\n{len(errs)} ERRORS"); sys.exit(1)
        n = sum(1 for c in data.values() for s in ("0", "1", "2") if c.get(s))
        print(f"all {n} builds valid ({len(data)} classes)")
    elif cmd == "generate":
        print(generate(data))
