// Generated by tools/boost-gear/gen.py - do not edit by hand.
// Per-archetype enchants and gems, verified against 3.3.5a SpellItemEnchantment.dbc.
#include "BoostGear.h"

namespace
{
  // Archetypes: 0 STR_MELEE, 1 TANK, 2 AGI_MELEE, 3 AGI_RANGED, 4 SP_CASTER, 5 HEALER.
  // Enchant SpellItemEnchantment id per EQUIPMENT_SLOT index (0 = none).
  const uint32 enchantBySlot[6][18] =
  {
    {3817, 0, 3808, 0, 3832, 0, 3823, 3826, 3845, 3231, 0, 0, 0, 0, 1099, 3789, 0, 0}, // STR_MELEE
    {3818, 0, 3811, 0, 3832, 0, 3822, 3232, 3850, 3253, 0, 0, 0, 0, 1951, 3789, 3849, 0}, // TANK
    {3817, 0, 3808, 0, 3832, 0, 3823, 3232, 3845, 3222, 0, 0, 0, 0, 1099, 2673, 2673, 0}, // AGI_MELEE
    {3817, 0, 3808, 0, 3832, 0, 3823, 3232, 3845, 3234, 0, 0, 0, 0, 1099, 3827, 0, 3608}, // AGI_RANGED
    {3820, 0, 3810, 0, 3832, 0, 3719, 3826, 2332, 3249, 0, 0, 0, 0, 3296, 3834, 0, 0}, // SP_CASTER
    {3819, 0, 3809, 0, 3832, 0, 3719, 3244, 2332, 3249, 0, 0, 0, 0, 3296, 3834, 0, 0}, // HEALER
  };

  // Gem enchant id per colour: [meta, red, yellow, blue] (0 = none).
  const uint32 gemByColor[6][4] =
  {
    {3628, 3518, 3549, 3536}, // STR_MELEE
    {3637, 3532, 3529, 3532}, // TANK
    {3628, 3519, 3554, 3537}, // AGI_MELEE
    {3628, 3519, 3554, 3537}, // AGI_RANGED
    {3621, 3520, 3531, 3538}, // SP_CASTER
    {3627, 3520, 3526, 3510}, // HEALER
  };

  int ArchetypeOf(uint32 classId, uint8 spec)
  {
    switch (classId)
    {
    case CLASS_WARRIOR:
      return spec == 0 ? 0 : spec == 1 ? 0 : 1;
    case CLASS_PALADIN:
      return spec == 0 ? 5 : spec == 1 ? 1 : 0;
    case CLASS_HUNTER:
      return spec == 0 ? 3 : spec == 1 ? 3 : 3;
    case CLASS_ROGUE:
      return spec == 0 ? 2 : spec == 1 ? 2 : 2;
    case CLASS_PRIEST:
      return spec == 0 ? 5 : spec == 1 ? 5 : 4;
    case CLASS_DEATH_KNIGHT:
      return spec == 0 ? 0 : spec == 1 ? 0 : 0;
    case CLASS_SHAMAN:
      return spec == 0 ? 4 : spec == 1 ? 2 : 5;
    case CLASS_MAGE:
      return spec == 0 ? 4 : spec == 1 ? 4 : 4;
    case CLASS_WARLOCK:
      return spec == 0 ? 4 : spec == 1 ? 4 : 4;
    case CLASS_DRUID:
      return spec == 0 ? 4 : spec == 1 ? 2 : 5;
    }
    return -1;
  }
}

static uint32 GetEnchant(uint32 classId, uint8 spec, uint8 slot)
{
  int a = ArchetypeOf(classId, spec);
  return (a < 0 || slot >= 18) ? 0 : enchantBySlot[a][slot];
}

static uint32 GetGem(uint32 classId, uint8 spec, uint32 color)
{
  int a = ArchetypeOf(classId, spec);
  if (a < 0)
  {
    return 0;
  }
  switch (color)
  {
  case 1: return gemByColor[a][0];
  case 2: return gemByColor[a][1];
  case 4: return gemByColor[a][2];
  case 8: return gemByColor[a][3];
  }
  return 0;
}

void BoostGear::ApplyEnchants(Player *player, uint8 specialization)
{
  for (uint8 slot = EQUIPMENT_SLOT_START; slot < EQUIPMENT_SLOT_TABARD; ++slot)
  {
    Item *item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
    if (!item)
    {
      continue;
    }
    uint32 ench = GetEnchant(player->getClass(), specialization, slot);
    if (!ench)
    {
      continue;
    }
    item->SetEnchantment(PERM_ENCHANTMENT_SLOT, ench, 0, 0);
    player->ApplyEnchantment(item, PERM_ENCHANTMENT_SLOT, true);
  }
}

void BoostGear::ApplyGems(Player *player, uint8 specialization)
{
  for (uint8 slot = EQUIPMENT_SLOT_START; slot < EQUIPMENT_SLOT_TABARD; ++slot)
  {
    Item *item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
    if (!item)
    {
      continue;
    }
    ItemTemplate const *proto = item->GetTemplate();
    for (uint8 i = 0; i < MAX_ITEM_PROTO_SOCKETS; ++i)
    {
      uint32 color = proto->Socket[i].Color;
      if (!color)
      {
        continue;
      }
      uint32 gem = GetGem(player->getClass(), specialization, color);
      if (!gem)
      {
        continue;
      }
      EnchantmentSlot es = EnchantmentSlot(SOCK_ENCHANTMENT_SLOT + i);
      item->SetEnchantment(es, gem, 0, 0);
      player->ApplyEnchantment(item, es, true);
    }
  }
}

