// Generated by tools/boost-glyphs/gen.py - do not edit by hand.
// Preset glyphs per class+spec (GlyphProperties ids), verified against the client DBCs.
#include "BoostGlyphs.h"
#include "DBCStores.h"

std::vector<uint32> BoostGlyphs::GetGlyphs(uint32 classId, uint8 spec)
{
  switch (classId)
  {
  case CLASS_WARRIOR:
    switch (spec)
    {
    case 0: // Arms
      return {489, 494, 505, 851, 483, 485};
    case 1: // Fury
      return {509, 496, 490, 851, 483, 485};
    case 2: // Protection
      return {502, 493, 764, 851, 483, 485};
    }
    break;
  case CLASS_PALADIN:
    switch (spec)
    {
    case 0: // Holy
      return {701, 196, 199, 455, 452, 457};
    case 1: // Protection
      return {561, 705, 190, 455, 452, 456};
    case 2: // Retribution
      return {183, 561, 189, 453, 456, 455};
    }
    break;
  case CLASS_HUNTER:
    switch (spec)
    {
    case 0: // Beast Mastery
      return {356, 368, 366, 441, 439, 440};
    case 1: // Marksmanship
      return {368, 366, 677, 441, 439, 440};
    case 2: // Survival
      return {691, 368, 366, 441, 439, 440};
    }
    break;
  case CLASS_ROGUE:
    switch (spec)
    {
    case 0: // Assassination
      return {733, 714, 732, 467, 468, 464};
    case 1: // Combat
      return {409, 406, 398, 467, 468, 464};
    case 2: // Subtlety
      return {404, 393, 716, 467, 468, 464};
    }
    break;
  case CLASS_PRIEST:
    switch (spec)
    {
    case 0: // Discipline
      return {263, 710, 255, 460, 463, 459};
    case 1: // Holy
      return {251, 709, 255, 460, 463, 459};
    case 2: // Shadow
      return {262, 269, 261, 463, 460, 459};
    }
    break;
  case CLASS_DEATH_KNIGHT:
    switch (spec)
    {
    case 0: // Blood
      return {772, 558, 532, 555, 553, 514};
    case 1: // Frost
      return {525, 521, 772, 555, 553, 514};
    case 2: // Unholy
      return {527, 520, 524, 555, 553, 514};
    }
    break;
  case CLASS_SHAMAN:
    switch (spec)
    {
    case 0: // Elemental
      return {752, 214, 219, 473, 475, 612};
    case 1: // Enhancement
      return {228, 231, 736, 473, 475, 552};
    case 2: // Restoration
      return {751, 216, 212, 473, 475, 552};
    }
    break;
  case CLASS_MAGE:
    switch (spec)
    {
    case 0: // Arcane
      return {651, 312, 326, 445, 451, 447};
    case 1: // Fire
      return {316, 328, 697, 445, 451, 447};
    case 2: // Frost
      return {319, 322, 871, 445, 451, 447};
    }
    break;
  case CLASS_WARLOCK:
    switch (spec)
    {
    case 0: // Affliction
      return {755, 760, 291, 478, 477, 479};
    case 1: // Demonology
      return {278, 756, 760, 478, 477, 479};
    case 2: // Destruction
      return {273, 283, 272, 478, 477, 479};
    }
    break;
  case CLASS_DRUID:
    switch (spec)
    {
    case 0: // Balance
      return {175, 180, 176, 613, 434, 435};
    case 1: // Feral
      return {166, 674, 165, 551, 434, 433};
    case 2: // Restoration
      return {672, 168, 673, 434, 433, 431};
    }
    break;
  default:
    break;
  }
  return {};
}

void BoostGlyphs::ApplyGlyphs(Player *player, uint8 specialization)
{
  if (specialization > 2)
  {
    specialization = 0;
  }

  std::vector<uint32> glyphList = GetGlyphs(player->getClass(), specialization);
  if (glyphList.empty())
  {
    return;
  }

  // Place each glyph into the first free slot whose type matches (major/minor).
  std::vector<bool> used(glyphList.size(), false);
  for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)
  {
    GlyphSlotEntry const *gs = sGlyphSlotStore.LookupEntry(player->GetGlyphSlot(slot));
    if (!gs)
    {
      continue;
    }

    for (size_t i = 0; i < glyphList.size(); ++i)
    {
      if (used[i])
      {
        continue;
      }
      GlyphPropertiesEntry const *gp = sGlyphPropertiesStore.LookupEntry(glyphList[i]);
      if (!gp || gp->TypeFlags != gs->TypeFlags)
      {
        continue;
      }
      if (uint32 oldGlyph = player->GetGlyph(slot))
      {
        if (GlyphPropertiesEntry const *oldGp = sGlyphPropertiesStore.LookupEntry(oldGlyph))
        {
          player->RemoveAurasDueToSpell(oldGp->SpellId);
        }
      }
      player->SetGlyph(slot, glyphList[i], true);
      player->CastSpell(player, gp->SpellId, true);
      used[i] = true;
      break;
    }
  }

  player->SendTalentsInfoData(false);
}

