#ifndef MOD_APPRECIATION_H
#define MOD_APPRECIATION_H

#include "ScriptMgr.h"

enum
{
  // Boost options, one per (targetLevel, equipmentTier) pair:
  // 0 = level 60, 1 = level 70, 2 = level 80 fresh, 3 = level 80 pre-raid, 4 = level 80 PVP.
  GOSSIP_MENU_CHOOSE_SPECIALIZATION_START = 100,
  GOSSIP_MENU_CHOOSE_SPECIALIZATION_END = 104,

  GOSSIP_MENU_SPECIALIZATION_START = 200,
  GOSSIP_MENU_SPECIALIZATION_1 = 200,
  GOSSIP_MENU_SPECIALIZATION_2 = 210,
  GOSSIP_MENU_SPECIALIZATION_3 = 220,
  GOSSIP_MENU_SPECIALIZATION_END = 224,

  GOSSIP_MENU_SPECIALIZATION_CONFIRM_START = 300,
  GOSSIP_MENU_SPECIALIZATION_CONFIRM_END = 324,

  GOSSIP_TEXT_DEFAULT = 48,
  GOSSIP_BOOST_TEXT_DEFAULT = 6000000,
  GOSSIP_BOOST_TEXT_DISABLE = 6000001,
  GOSSIP_BOOST_TEXT_LEVEL_TOO_HIGH = 6000002,
  GOSSIP_BOOST_TEXT_CHOOSE_SPECIALIZATION = 6000003,
  GOSSIP_BOOST_TEXT_CONFIRM_SPECIALIZATION = 6000004,
};

#endif